[2022-07-09T13:03:44.777] [ERROR] error - TypeError: util.fail is not a function
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\routes\users.js:24:21)
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:700:16)
    at Generator.next (<anonymous>)
    at Object.allowedMethods (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:369:5)
    at allowedMethods.next (<anonymous>)
    at Object.dispatch (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)
    at Object.serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:43:7)
    at serve.next (<anonymous>)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:65:19)
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:50:10)
    at Object.toPromise (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:118:63)
    at next (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:99:29)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:69:7)
[2022-07-09T13:06:39.239] [ERROR] error - TypeError: util.fail is not a function
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\routes\users.js:24:21)
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:700:16)
    at Generator.next (<anonymous>)
    at Object.allowedMethods (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:369:5)
    at allowedMethods.next (<anonymous>)
    at Object.dispatch (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)
    at Object.serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:43:7)
    at serve.next (<anonymous>)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:65:19)
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:50:10)
    at Object.toPromise (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:118:63)
    at next (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:99:29)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:69:7)
[2022-07-09T13:07:26.834] [ERROR] error - TypeError: util.fail is not a function
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\routes\users.js:24:21)
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:700:16)
    at Generator.next (<anonymous>)
    at Object.allowedMethods (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:369:5)
    at allowedMethods.next (<anonymous>)
    at Object.dispatch (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)
    at Object.serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:43:7)
    at serve.next (<anonymous>)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:65:19)
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:50:10)
    at Object.toPromise (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:118:63)
    at next (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:99:29)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:69:7)
[2022-07-09T13:09:13.688] [ERROR] error - TypeError: util.fail is not a function
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\routes\users.js:24:21)
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:700:16)
    at Generator.next (<anonymous>)
    at Object.allowedMethods (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:369:5)
    at allowedMethods.next (<anonymous>)
    at Object.dispatch (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)
    at Object.serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:43:7)
    at serve.next (<anonymous>)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:65:19)
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:50:10)
    at Object.toPromise (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:118:63)
    at next (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:99:29)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:69:7)
[2022-07-09T13:09:35.965] [ERROR] error - TypeError: util.fail is not a function
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\routes\users.js:24:21)
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:700:16)
    at Generator.next (<anonymous>)
    at Object.allowedMethods (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:369:5)
    at allowedMethods.next (<anonymous>)
    at Object.dispatch (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)
    at Object.serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:43:7)
    at serve.next (<anonymous>)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:65:19)
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:50:10)
    at Object.toPromise (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:118:63)
    at next (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:99:29)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:69:7)
[2022-07-09T13:14:44.597] [ERROR] error - TypeError: util.fail is not a function
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\routes\users.js:24:21)
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:700:16)
    at Generator.next (<anonymous>)
    at Object.allowedMethods (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:369:5)
    at allowedMethods.next (<anonymous>)
    at Object.dispatch (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)
    at Object.serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:43:7)
    at serve.next (<anonymous>)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:65:19)
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:50:10)
    at Object.toPromise (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:118:63)
    at next (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:99:29)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:69:7)
[2022-07-09T14:01:26.251] [ERROR] error - TypeError: util.fail is not a function
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\routes\users.js:24:21)
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:700:16)
    at Generator.next (<anonymous>)
    at Object.allowedMethods (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:369:5)
    at allowedMethods.next (<anonymous>)
    at Object.dispatch (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)
    at Object.serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:43:7)
    at serve.next (<anonymous>)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:65:19)
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:50:10)
    at Object.toPromise (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:118:63)
    at next (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:99:29)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:69:7)
[2022-07-09T14:45:54.723] [ERROR] error - ReferenceError: dasdas is not defined
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\routes\users.js:11:3)
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:700:16)
    at Generator.next (<anonymous>)
    at Object.allowedMethods (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:369:5)
    at allowedMethods.next (<anonymous>)
    at Object.dispatch (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)
    at Object.serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:43:7)
    at serve.next (<anonymous>)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:65:19)
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:50:10)
    at Object.toPromise (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:118:63)
    at next (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:99:29)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:69:7)
[2022-07-09T14:45:54.968] [ERROR] error - ReferenceError: dasdas is not defined
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\routes\users.js:11:3)
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:700:16)
    at Generator.next (<anonymous>)
    at Object.allowedMethods (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:369:5)
    at allowedMethods.next (<anonymous>)
    at Object.dispatch (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)
    at Object.serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:43:7)
    at serve.next (<anonymous>)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:65:19)
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:50:10)
    at Object.toPromise (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:118:63)
    at next (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:99:29)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:69:7)
[2022-07-09T14:45:55.128] [ERROR] error - ReferenceError: dasdas is not defined
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\routes\users.js:11:3)
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:700:16)
    at Generator.next (<anonymous>)
    at Object.allowedMethods (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:369:5)
    at allowedMethods.next (<anonymous>)
    at Object.dispatch (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)
    at Object.serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:43:7)
    at serve.next (<anonymous>)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:65:19)
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:50:10)
    at Object.toPromise (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:118:63)
    at next (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:99:29)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:69:7)
[2022-07-09T14:45:55.293] [ERROR] error - ReferenceError: dasdas is not defined
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\routes\users.js:11:3)
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:700:16)
    at Generator.next (<anonymous>)
    at Object.allowedMethods (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:369:5)
    at allowedMethods.next (<anonymous>)
    at Object.dispatch (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)
    at Object.serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:43:7)
    at serve.next (<anonymous>)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:65:19)
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:50:10)
    at Object.toPromise (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:118:63)
    at next (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:99:29)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:69:7)
[2022-07-09T14:45:55.489] [ERROR] error - ReferenceError: dasdas is not defined
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\routes\users.js:11:3)
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:700:16)
    at Generator.next (<anonymous>)
    at Object.allowedMethods (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:369:5)
    at allowedMethods.next (<anonymous>)
    at Object.dispatch (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)
    at Object.serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:43:7)
    at serve.next (<anonymous>)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:65:19)
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:50:10)
    at Object.toPromise (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:118:63)
    at next (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:99:29)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:69:7)
[2022-07-09T14:45:55.603] [ERROR] error - ReferenceError: dasdas is not defined
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\routes\users.js:11:3)
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:700:16)
    at Generator.next (<anonymous>)
    at Object.allowedMethods (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:369:5)
    at allowedMethods.next (<anonymous>)
    at Object.dispatch (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)
    at Object.serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:43:7)
    at serve.next (<anonymous>)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:65:19)
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:50:10)
    at Object.toPromise (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:118:63)
    at next (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:99:29)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:69:7)
[2022-07-09T14:46:26.938] [ERROR] error - ReferenceError: dasdas is not defined
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\routes\users.js:11:3)
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:700:16)
    at Generator.next (<anonymous>)
    at Object.allowedMethods (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:369:5)
    at allowedMethods.next (<anonymous>)
    at Object.dispatch (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)
    at Object.serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:43:7)
    at serve.next (<anonymous>)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:65:19)
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:50:10)
    at Object.toPromise (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:118:63)
    at next (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:99:29)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:69:7)
[2022-07-09T14:46:30.082] [ERROR] error - ReferenceError: dasdas is not defined
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\routes\users.js:11:3)
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:700:16)
    at Generator.next (<anonymous>)
    at Object.allowedMethods (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:369:5)
    at allowedMethods.next (<anonymous>)
    at Object.dispatch (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)
    at Object.serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:43:7)
    at serve.next (<anonymous>)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:65:19)
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:50:10)
    at Object.toPromise (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:118:63)
    at next (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:99:29)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:69:7)
[2022-07-09T14:46:42.727] [ERROR] error - ReferenceError: dasdas is not defined
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\routes\users.js:11:3)
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:700:16)
    at Generator.next (<anonymous>)
    at Object.allowedMethods (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:369:5)
    at allowedMethods.next (<anonymous>)
    at Object.dispatch (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)
    at Object.serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:43:7)
    at serve.next (<anonymous>)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:65:19)
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:50:10)
    at Object.toPromise (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:118:63)
    at next (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:99:29)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:69:7)
[2022-07-09T14:48:33.530] [ERROR] error - TypeError: Cannot read property 'body' of undefined
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\routes\users.js:13:47)
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:700:16)
    at Generator.next (<anonymous>)
    at Object.allowedMethods (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:369:5)
    at allowedMethods.next (<anonymous>)
    at Object.dispatch (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)
    at Object.serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:43:7)
    at serve.next (<anonymous>)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:65:19)
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:50:10)
    at Object.toPromise (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:118:63)
    at next (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:99:29)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:69:7)
[2022-07-09T14:51:09.646] [ERROR] error - TypeError: Cannot read property 'body' of undefined
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\routes\users.js:11:27)
    at Object.<anonymous> (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:700:16)
    at Generator.next (<anonymous>)
    at Object.allowedMethods (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:369:5)
    at allowedMethods.next (<anonymous>)
    at Object.dispatch (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-router\lib\router.js:334:5)
    at dispatch.next (<anonymous>)
    at Object.serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:43:7)
    at serve.next (<anonymous>)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:65:19)
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:50:10)
    at Object.toPromise (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:118:63)
    at next (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:99:29)
    at onFulfilled (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\co\index.js:69:7)
[2022-07-09T23:11:32.385] [ERROR] error - TypeError: Cannot read property 'AUTH_ERROR' of undefined
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\app.js:41:51
    at async F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\app.js:38:3
    at async serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:53:9)
    at async logger (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-logger\index.js:67:7)
    at async bodyParser (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-bodyparser\index.js:95:5)
[2022-07-09T23:11:33.741] [ERROR] error - TypeError: Cannot read property 'AUTH_ERROR' of undefined
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\app.js:41:51
    at async F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\app.js:38:3
    at async serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:53:9)
    at async logger (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-logger\index.js:67:7)
    at async bodyParser (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-bodyparser\index.js:95:5)
[2022-07-09T23:11:38.426] [ERROR] error - TypeError: Cannot read property 'AUTH_ERROR' of undefined
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\app.js:41:51
    at async F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\app.js:38:3
    at async serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:53:9)
    at async logger (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-logger\index.js:67:7)
    at async bodyParser (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-bodyparser\index.js:95:5)
[2022-07-09T23:11:38.436] [ERROR] error - TypeError: Cannot read property 'AUTH_ERROR' of undefined
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\app.js:41:51
    at async F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\app.js:38:3
    at async serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:53:9)
    at async logger (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-logger\index.js:67:7)
    at async bodyParser (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-bodyparser\index.js:95:5)
[2022-07-09T23:11:57.558] [ERROR] error - TypeError: Cannot read property 'AUTH_ERROR' of undefined
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\app.js:41:51
    at async F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\app.js:38:3
    at async serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:53:9)
    at async logger (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-logger\index.js:67:7)
    at async bodyParser (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-bodyparser\index.js:95:5)
[2022-07-09T23:11:57.562] [ERROR] error - TypeError: Cannot read property 'AUTH_ERROR' of undefined
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\app.js:41:51
    at async F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\app.js:38:3
    at async serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:53:9)
    at async logger (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-logger\index.js:67:7)
    at async bodyParser (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-bodyparser\index.js:95:5)
[2022-07-09T23:13:19.168] [ERROR] error - TypeError: Cannot read property 'AUTH_ERROR' of undefined
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\app.js:41:51
    at async F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\app.js:38:3
    at async serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:53:9)
    at async logger (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-logger\index.js:67:7)
    at async bodyParser (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-bodyparser\index.js:95:5)
[2022-07-09T23:13:19.302] [ERROR] error - TypeError: Cannot read property 'AUTH_ERROR' of undefined
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\app.js:41:51
    at async F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\app.js:38:3
    at async serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:53:9)
    at async logger (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-logger\index.js:67:7)
    at async bodyParser (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-bodyparser\index.js:95:5)
[2022-07-09T23:14:20.961] [ERROR] error - UnauthorizedError: Bad Authorization header format. Format is "Authorization: Bearer <token>"
    at Object.throw (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa\lib\context.js:97:11)
    at resolveAuthorizationHeader (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-jwt\lib\resolvers\auth-header.js:26:18)
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-jwt\lib\index.js:20:49
    at Array.find (<anonymous>)
    at jwt (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-jwt\lib\index.js:20:24)
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-unless\index.js:29:12
    at dispatch (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\app.js:38:9
    at dispatch (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at views (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-views\src\index.js:91:12)
    at dispatch (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:53:15)
    at async logger (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-logger\index.js:67:7)
    at async bodyParser (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-bodyparser\index.js:95:5)
[2022-07-09T23:14:21.105] [ERROR] error - UnauthorizedError: Bad Authorization header format. Format is "Authorization: Bearer <token>"
    at Object.throw (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa\lib\context.js:97:11)
    at resolveAuthorizationHeader (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-jwt\lib\resolvers\auth-header.js:26:18)
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-jwt\lib\index.js:20:49
    at Array.find (<anonymous>)
    at jwt (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-jwt\lib\index.js:20:24)
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-unless\index.js:29:12
    at dispatch (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\app.js:38:9
    at dispatch (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at views (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-views\src\index.js:91:12)
    at dispatch (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:53:15)
    at async logger (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-logger\index.js:67:7)
    at async bodyParser (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-bodyparser\index.js:95:5)
[2022-07-09T23:17:20.035] [ERROR] error - UnauthorizedError: Bad Authorization header format. Format is "Authorization: Bearer <token>"
    at Object.throw (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa\lib\context.js:97:11)
    at resolveAuthorizationHeader (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-jwt\lib\resolvers\auth-header.js:26:18)
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-jwt\lib\index.js:20:49
    at Array.find (<anonymous>)
    at jwt (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-jwt\lib\index.js:20:24)
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-unless\index.js:29:12
    at dispatch (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\app.js:38:9
    at dispatch (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at views (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-views\src\index.js:91:12)
    at dispatch (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:53:15)
    at async logger (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-logger\index.js:67:7)
    at async bodyParser (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-bodyparser\index.js:95:5)
[2022-07-09T23:17:20.140] [ERROR] error - UnauthorizedError: Bad Authorization header format. Format is "Authorization: Bearer <token>"
    at Object.throw (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa\lib\context.js:97:11)
    at resolveAuthorizationHeader (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-jwt\lib\resolvers\auth-header.js:26:18)
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-jwt\lib\index.js:20:49
    at Array.find (<anonymous>)
    at jwt (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-jwt\lib\index.js:20:24)
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-unless\index.js:29:12
    at dispatch (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\app.js:38:9
    at dispatch (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at views (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-views\src\index.js:91:12)
    at dispatch (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:53:15)
    at async logger (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-logger\index.js:67:7)
    at async bodyParser (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-bodyparser\index.js:95:5)
[2022-07-09T23:17:41.635] [ERROR] error - TypeError: Cannot read property 'AUTH_ERROR' of undefined
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\app.js:42:51
    at async F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\app.js:38:3
    at async serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:53:9)
    at async logger (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-logger\index.js:67:7)
    at async bodyParser (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-bodyparser\index.js:95:5)
[2022-07-09T23:17:41.934] [ERROR] error - TypeError: Cannot read property 'AUTH_ERROR' of undefined
    at F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\app.js:42:51
    at async F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\app.js:38:3
    at async serve (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-static\index.js:53:9)
    at async logger (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-logger\index.js:67:7)
    at async bodyParser (F:\Program\NodeJS\koa\Vue3-ElementPlus-Koa2\manager-server\node_modules\koa-bodyparser\index.js:95:5)
